name: PNGToJPEG
options:
  deploymentTarget:
    macOS: 12.0
targets:
  PNGToJPEG:
    type: application
    platform: macOS
    sources:
      - App.swift
      - ContentView.swift
    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: com.example.PNGToJPEG
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
